
spring:
  application:
    name: Config-Dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    prefer-ip-address: 'true'
